// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7xKaTImckBS0aZ8o6bIuJfXXyhG34o-Q',
    appId: '1:320260735254:web:d136acde7b808b12fdd037',
    messagingSenderId: '320260735254',
    projectId: 'fypkonnectjob',
    authDomain: 'fypkonnectjob.firebaseapp.com',
    storageBucket: 'fypkonnectjob.appspot.com',
    measurementId: 'G-GFZPVE2KB7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFXA1uMpgUkx-W-ah4oOXnouIe5BTLxxw',
    appId: '1:320260735254:android:0651a17d433704acfdd037',
    messagingSenderId: '320260735254',
    projectId: 'fypkonnectjob',
    storageBucket: 'fypkonnectjob.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxUWqQpHE83XaVtPfNzZWSRbYJgyGABU0',
    appId: '1:320260735254:ios:966bd8cea2049104fdd037',
    messagingSenderId: '320260735254',
    projectId: 'fypkonnectjob',
    storageBucket: 'fypkonnectjob.appspot.com',
    iosBundleId: 'com.example.booksexchange',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxUWqQpHE83XaVtPfNzZWSRbYJgyGABU0',
    appId: '1:320260735254:ios:966bd8cea2049104fdd037',
    messagingSenderId: '320260735254',
    projectId: 'fypkonnectjob',
    storageBucket: 'fypkonnectjob.appspot.com',
    iosBundleId: 'com.example.booksexchange',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7xKaTImckBS0aZ8o6bIuJfXXyhG34o-Q',
    appId: '1:320260735254:web:762d2e8b41a22065fdd037',
    messagingSenderId: '320260735254',
    projectId: 'fypkonnectjob',
    authDomain: 'fypkonnectjob.firebaseapp.com',
    storageBucket: 'fypkonnectjob.appspot.com',
    measurementId: 'G-SEQ40MLH4D',
  );
}
